"""adds ecommerce stores table

Revision ID: 36513b67d28c
Revises: b88cd221301f
Create Date: 2025-12-20 14:06:34.923065

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = '36513b67d28c'
down_revision: Union[str, Sequence[str], None] = 'b88cd221301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce_stores',
    sa.Column('available_tlds', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False, default=datetime.now()),
    sa.Column('description', sqltypes.AutoString(length=150), nullable=True),
    sa.Column('domain_name', sqltypes.AutoString(length=60), nullable=False),
    sa.Column('id', sa.String(26), nullable=False),
    sa.Column('logo_url', sqltypes.AutoString(length=250), nullable=True),
    sa.Column('market_type', sa.Enum('B2B', 'B2C', 'C2C', name='market_type'), nullable=False, default='B2C'),
    sa.Column('name', sqltypes.AutoString(length=30), nullable=False),
    sa.Column('platform_id', sqltypes.AutoString(), nullable=True),
    sa.Column('product_detail_uri_regex', sqltypes.AutoString(length=250), nullable=True),
    sa.Column('store_type', sa.Enum('MARKETPLACE', 'ONLINE_STORE', name='store_type'), nullable=False, default='ONLINE_STORE'),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), nullable=False, default=datetime.now()),
    sa.ForeignKeyConstraint(['platform_id'], ['ecommerce_platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecommerce_stores')
    # ### end Alembic commands ###
