"""updates ecommerce_platform_signatures constraints

Revision ID: 961bcd17822b
Revises: 36513b67d28c
Create Date: 2025-12-22 22:20:33.104283

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '961bcd17822b'
down_revision: Union[str, Sequence[str], None] = '36513b67d28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('type_platform_id_constraint', 'ecommerce_platform_signatures', ['type', 'platform_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('type_platform_id_constraint', 'ecommerce_platform_signatures', type_='unique')
    # ### end Alembic commands ###
