"""adds accounts table

Revision ID: a57a6376061b
Revises: 
Create Date: 2025-12-09 22:16:03.305819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a57a6376061b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
        sa.Column(
            'created_on', 
            sa.DateTime(timezone=True), 
            nullable=False, 
            server_default=sa.text('CURRENT_TIMESTAMP')
        ),
        sa.Column('credits', sa.Float(2), nullable=False, default=0),
        sa.Column('email', sqltypes.AutoString(length=60), nullable=False),
        sa.Column('first_name', sqltypes.AutoString(length=30), nullable=False),
        sa.Column('home_ip_address', sa.String(), nullable=True),
        sa.Column('id', sa.String(26), nullable=False),
        sa.Column('last_name', sqltypes.AutoString(length=30), nullable=True),
        sa.Column('password_hash', sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
