"""adds ecomm tables

Revision ID: b88cd221301f
Revises: a57a6376061b
Create Date: 2025-12-19 17:54:22.054001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b88cd221301f'
down_revision: Union[str, Sequence[str], None] = 'a57a6376061b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce_platforms',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('logo_url', sqltypes.AutoString(length=250), nullable=True),
        sa.Column('name', sqltypes.AutoString(length=30), nullable=False),
        sa.Column('url', sqltypes.AutoString(length=250), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('ecommerce_platform_signatures',
        sa.Column('confidence', sa.Integer(), nullable=True, default=10),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('COOKIES', 'JS_OBJECTS', 'META', 'ASSET_DOMAIN', 'ENDPOINT', 'PATH', 'BODY_CLASS', 'QUERY_PARAM', 'CHECKOUT_URL', 'HTML_ATTRIBUTE', 'SCRIPT', 'IFRAME', 'HTML_COMMENT', name='fingerprint_type'), nullable=False),
        sa.Column('values', sa.ARRAY(sa.String(100)), nullable=True),
        sa.Column('platform_id', sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['platform_id'], ['ecommerce_platforms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('accounts', 'credits',
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'credits',
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=False)
    op.drop_table('ecommerce_platform_signatures')
    op.drop_table('ecommerce_platforms')
    # ### end Alembic commands ###
